### ISSUE TITLE
Check UI behavior for Tablet Emulator 

### ISSUE THREAD

**Issue by bryanbauzon** [bryanbauzon/healthcare-app#12]
As per the latest commit https://github.com/bryanbauzon/healthcare-app/commit/b9b0648eb898bc36dd8dcfaaf6dd48b705eba446 (07 January 2024), please check the possible UI issue for the Tablet emulator.
* To check all screen
*

**Comment by RaxelJosh** [comment]
Done Checking and Adjusted app icon on Login to fix pixel excess issues on tablet
