### ISSUE TITLE
App Release 0.0.1

### ISSUE THREAD

**Issue by RaxelJosh** [bryanbauzon/healthcare-app#16]
Find a alternative Place to release the app on 0.0.1 version

**Comment by bryanbauzon** [comment]
https://www.dropbox.com/

**Comment by bryanbauzon** [comment]
Please refer to https://www.dropbox.com/scl/fi/wrbdsno4wgxkk376zlxx5/app-v.0.0.1.apk?rlkey=yeo3soaozw53uxa0gb0kmnteb&dl=0 for the app release.
