### ISSUE TITLE
Jumbled Value After Save For Now

### ISSUE THREAD

**Issue by RaxelJosh** [bryanbauzon/healthcare-app#2]
After having inputs and clicking save for now when closing the apps the original inputs are not on the intended field value
please see attached picture
![for comparison 1](https://github.com/bryanbauzon/healthcare-app/assets/84169331/38326393-43ad-4f13-ba23-d3c6c16375b8)
![for comparison 2](https://github.com/bryanbauzon/healthcare-app/assets/84169331/04c4a1a0-a207-464b-9cc8-5850e60e2bde)

**Comment by bryanbauzon** [comment]
Hi @RaxelJosh, this is fixed on the latest commit. Thank you! :D
