### ISSUE TITLE
Modify BP Field

### ISSUE THREAD

**Issue by RaxelJosh** [bryanbauzon/healthcare-app#6]
Modify bp Field see Attached Sample
![image](https://github.com/bryanbauzon/healthcare-app/assets/84169331/8e1460eb-f69d-4b7e-99f4-16f916c9a5d4)
![image](https://github.com/bryanbauzon/healthcare-app/assets/84169331/a7936de5-8d35-4537-bdc9-44a56b511b3e)

Please also see attached link for BP Name Value
https://www.webmd.com/hypertension-high-blood-pressure/diastolic-and-systolic-blood-pressure-know-your-numbers

**Comment by bryanbauzon** [comment]
<img width="425" alt="Screenshot 2023-12-09 at 11 03 11 PM" src="https://github.com/bryanbauzon/healthcare-app/assets/35340090/2fcfbf08-c117-41f1-85bc-e8521a118836">
<img width="500" alt="Screenshot 2023-12-09 at 11 04 57 PM" src="https://github.com/bryanbauzon/healthcare-app/assets/35340090/53585009-45ec-4273-8066-bdcafac4e96a">
